### ISSUE TITLE
Add minecraft version in info job;

### ISSUE THREAD

**Issue by HarvelsX** [Timoti11/quasar#6]
https://github.com/Timoti11/quasar/blob/9a0a61b4004fd31b0b9ab9f7ee723020252984c5/.github/workflows/packwiz.yml#L6

```yml
    runs-on: ubuntu-latest
    outputs:
      mcversion: ${{ steps.info.outputs.mcversion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Prepare environment
        run: GO111MODULE=on go install github.com/freshautomations/stoml@latest
      - name: Get info
        id: info
        run: |
            mcversion=`stoml pack.toml versions.minecraft`
            echo "::set-output name=mcversion::$mcversion"
```

And

```yml
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [info, build]
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.info.outputs.name }} ${{ needs.info.outputs.version }} for ${{ needs.info.outputs.mcversion }}
```
